# Generated by Django 5.1.5 on 2025-01-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_unit_product_with_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('pcs', 'Pieces')], default='piece', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='with_ingredients',
            field=models.CharField(choices=[('with', 'With Ingredients'), ('without', 'Without Ingredients')], default='with', max_length=10),
        ),
    ]
