# Generated by Django 5.1.5 on 2025-01-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_unit_alter_product_with_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='addIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('pcs', 'Pieces')], default='pcs', max_length=10)),
                ('stock', models.PositiveIntegerField()),
                ('minimum_stock', models.PositiveIntegerField()),
                ('with_supplier', models.CharField(choices=[('with', 'With Supplier'), ('without', 'Without Supplier')], default='with', max_length=10)),
                ('supplier_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_address', models.CharField(max_length=100)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='addProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('with_ingredients', models.CharField(choices=[('with', 'With Ingredients'), ('without', 'Without Ingredients')], default='with', max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('minimum_stock', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
