# Generated by Django 5.1.5 on 2025-01-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_addcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addingredient',
            old_name='with_supplier',
            new_name='supplier',
        ),
    ]
