# Generated by Django 5.1.5 on 2025-01-29 10:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_with_supplier_addingredient_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addingredient',
            old_name='name',
            new_name='ingredient_name',
        ),
        migrations.RenameField(
            model_name='addingredient',
            old_name='unit',
            new_name='unit_of_measurement',
        ),
        migrations.RemoveField(
            model_name='addingredient',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='addingredient',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='addingredient',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='addingredient',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='addingredient',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='addingredient',
            name='expiration_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='addSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_address', models.CharField(max_length=100)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addingredient')),
            ],
        ),
    ]
