# Generated by Django 5.1.5 on 2025-01-29 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_name_addingredient_ingredient_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit_of_Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='addingredient',
            name='unit_of_measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unit_of_measurement'),
        ),
    ]
