# Generated by Django 5.1.5 on 2025-01-29 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_unit_of_measurement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('with_ingredients', models.CharField(choices=[('with', 'With Ingredients'), ('without', 'Without Ingredients')], default='with', max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('minimum_stock', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='addCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='addSupplier',
            new_name='Supplier',
        ),
        migrations.DeleteModel(
            name='addProduct',
        ),
        migrations.RenameModel(
            old_name='addIngredient',
            new_name='Ingredient',
        ),
        migrations.AddField(
            model_name='productingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredient'),
        ),
        migrations.AddField(
            model_name='productingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='api.ProductIngredient', to='api.ingredient'),
        ),
    ]
