# Generated by Django 5.1.5 on 2025-01-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimum_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
