# Generated by Django 5.1.5 on 2025-01-30 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_accessrights_person_role_remove_product_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.person')),
                ('password', models.CharField(max_length=100)),
            ],
            bases=('api.person',),
        ),
    ]
