# Generated by Django 5.1.5 on 2025-01-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_count', models.PositiveIntegerField(default=0)),
                ('booking_date', models.DateField()),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('payment_status', models.CharField(choices=[('pp', 'Partially Paid'), ('fp', 'Fully Paid'), ('p', 'Pending')], default='p', max_length=10)),
                ('booking_status', models.CharField(choices=[('s', 'Success'), ('c', 'Cancelled'), ('p', 'Pending')], default='p', max_length=10)),
            ],
        ),
    ]
