# Generated by Django 5.1.5 on 2025-01-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='with_ingredients',
        ),
        migrations.AddField(
            model_name='product',
            name='with_ingredients',
            field=models.ManyToManyField(to='api.ingredient'),
        ),
    ]
