# Generated by Django 5.1.5 on 2025-01-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_product_with_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='with_ingredients',
            new_name='ingredients',
        ),
    ]
