# Generated by Django 5.1.5 on 2025-02-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_name_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit_of_measurement',
            old_name='type',
            new_name='unit_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='unit_of_measurement',
            name='unit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
