# Generated by Django 5.1.5 on 2025-02-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_type_unit_of_measurement_unit_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_of_measurement',
            name='unit',
            field=models.CharField(default='g', max_length=100),
        ),
    ]
