# Generated by Django 5.1.5 on 2025-03-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_booking_customer_booking_customer_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('S', 'Success'), ('C', 'Cancelled'), ('P', 'Pending')], default='p', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PP', 'Partially Paid'), ('F', 'Fully Paid'), ('P', 'Pending'), ('R', 'Refunded')], default='p', max_length=10),
        ),
    ]
