# Generated by Django 5.1.5 on 2025-03-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('A', 'Partially Paid'), ('F', 'Fully Paid'), ('P', 'Pending'), ('R', 'Refunded')], default='p', max_length=10),
        ),
    ]
