# Generated by Django 5.1.5 on 2025-03-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('S', 'Success'), ('C', 'Cancelled'), ('P', 'Pending')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('A', 'Partially Paid'), ('F', 'Fully Paid'), ('P', 'Pending'), ('R', 'Refunded')], default='P', max_length=10),
        ),
    ]
