# Generated by Django 5.1.5 on 2025-03-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role_type',
        ),
        migrations.AddField(
            model_name='role',
            name='access_rights',
            field=models.ManyToManyField(blank=True, to='api.accessrights'),
        ),
        migrations.AlterField(
            model_name='accessrights',
            name='feature_name',
            field=models.CharField(choices=[('create_order', 'Create Order'), ('orders_list', 'Orders List'), ('financial', 'Financial'), ('inventory', 'Inventory'), ('booking', 'Booking'), ('employee', 'Employee Management')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
